

// / FIREBASE AUTH ACTIONS
export const LOGIN_WITH_PROVIDER_FIREBASE = 'LOGIN_WITH_PROVIDER_FIREBASE';
export const REGISTER_FIREBASE_USER = 'REGISTER_FIREBASE_USER';
export const LOGIN_FIREBASE_USER = 'LOGIN_FIREBASE_USER';
export const FETCH_FIREBASE_USER = 'FETCH_FIREBASE_USER';
export const UPDATE_FIREBASE_USER = 'UPDATE_FIREBASE_USER';
export const CHANGE_FIREBASE_USER_PASSWORD = 'CHANGE_FIREBASE_USER_PASSWORD';
export const FIREBASE_PASSWORD_RESET_EMAIL = 'FIREBASE_PASSWORD_RESET_EMAIL';
export const LOGOUT_FIREBASE_USER = 'LOGOUT_FIREBASE_USER';

// EXPENSE ACTIONS
export const SELECT_IMAGE = 'SELECT_IMAGE';
export const ADD_IMAGE = "ADD_IMAGE";
export const ADD_IMAGE_FAILURE = "ADD_IMAGE_FAILURE";
export const ADD_EXPENSE = 'ADD_EXPENSE';
//export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
export const ADD_NOTES = 'ADD_NOTES';
export const ADD_NOTES_FAILURE = 'ADD_NOTES_FAILURE';
export const ADD_EXPENSE_DBKEY = 'ADD_EXPENSE_DBKEY';
export const ADD_DATE = 'ADD_DATE';
export const RESET_EXPENSE = 'RESET_EXPENSE';
export const UPDATE_IMAGE = 'UPDATE_IMAGE';
export const UPDATE_IMAGES = 'UPDATE_IMAGES';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const EDITED_EXPENSE = 'EDITED_EXPENSE';

// EXPENSES LIST ACTIONS
export const SET_FILTERED_EXPENSES = 'SET_FILTERED_EXPENSES';
export const SET_SORTBY = 'SET_SORTBY';
export const SET_SORTDIR = 'SET_SORTDIR';
export const SET_STARTDATE = 'SET_STARTDATE';
export const SET_ENDDATE = 'SET_ENDDATE';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';